import { SuccessAlert } from "@/components/Alerts";
import { Container } from "@/components/layout/SideBar";
import OuGroupRelationsFields from "@/components/ougrouprelations/OuGroupRelationFields";
import { OuGroupRelation } from "@/lib/apis/payments";
import { getOuGroupRelationById, updateOuGroupRelation } from "@/lib/apis/payments/client";
import { useApiRequest } from "@/lib/hooks/useApiRequest";
import { displayErrors } from "@/lib/utils";
import Head from "next/head";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const Update = () => {
    const { data, isLoading, executeRequest } = useApiRequest(getOuGroupRelationById);
    const { errors: updateErrors, isLoading: updating, executeRequest: updateRequest } = useApiRequest(updateOuGroupRelation);
    const [showUpdated, setShowUpdated] = useState(false);
    const [ouGroupRelation, setOuGroupRelation] = useState<OuGroupRelation | undefined>(undefined);
    const router = useRouter()
    const { id } = router.query


    useEffect(() => {
        if (!id) return;
        executeRequest(parseInt(id as string))
    }, [id]);

    useEffect(() => {
        setOuGroupRelation(data?.ouGroupRelation);
        if (data && data.ouGroupRelation) {
        }

    }, [data]);

    const formDisabled = () => isLoading || updating;

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        if (!ouGroupRelation) return;

        const ok = await updateRequest(ouGroupRelation);
        if (ok) {
            setShowUpdated(true);
            setTimeout(() => setShowUpdated(false), 1500);
        }
    }

    if (!ouGroupRelation || !data || !data.groups) return null;

    return (
        <>
            <Head>
                <title>Editar persona - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain narrow>
                <PageHeader title="Editar relació UO" subtitle={ouGroupRelation.groupMail} back={{ href: "/admin/ougrouprelations", text: "Relacions UO" }} />
                <div className="card p-6 sm:p-8">
                    {showUpdated && <div className="mb-5"><SuccessAlert text="Relació actualitzada correctament" /></div>}
                    <form action="#" method="post" onSubmit={onFormSubmit} autoComplete="off">
                        <OuGroupRelationsFields
                            groupSelector={{ selected: ouGroupRelation.groupId, options: data.groups.options }}
                            ouGroupRelation={ouGroupRelation}
                            setOuGroupRelation={setOuGroupRelation}
                            errors={updateErrors}
                        />

                        <div>
                            <input
                                disabled={formDisabled()}
                                className="btn btn-primary mt-8 w-full"
                                value="Actualitzar"
                                type="submit" />
                        </div>
                    </form>
                </div>
            </PageMain>
        </>
    )
}

export default function UpdateUoGroupRelationPage() {
    return (
        <Container>
            <Update />
        </Container>
    )
};