import { SuccessAlert } from "@/components/Alerts";
import { Container } from "@/components/layout/SideBar";
import OuGroupRelationsFields from "@/components/ougrouprelations/OuGroupRelationFields";
import { OuGroupRelation } from "@/lib/apis/payments";
import { createOuGroupRelation, getGroupsSelector } from "@/lib/apis/payments/client";
import { useApiRequest, useStartApiRequest } from "@/lib/hooks/useApiRequest";
import { displayErrors } from "@/lib/utils";
import Head from "next/head";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const defaultOuGroupRelation: OuGroupRelation = {
    activeOu: "",
    oldOu: "",
    changePasswordNextSignIn: false,
    updatePassword: false,
    id: 0,
    groupId: 0,
    groupMail: "",
}

const Create = () => {
    const { data: groups, isLoading } = useStartApiRequest(getGroupsSelector);
    const { errors: updateErrors, isLoading: creating, executeRequest: updateRequest } = useApiRequest(createOuGroupRelation);
    const [showCreated, setShowCreated] = useState(false);
    const [ouGroupRelation, setOuGroupRelation] = useState<OuGroupRelation>(defaultOuGroupRelation);

    const formDisabled = () => isLoading || creating;

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        if (!ouGroupRelation) return;

        const ok = await updateRequest(ouGroupRelation);
        if (ok) {
            setShowCreated(true);
        }
    }

    if (!groups) return null;

    return (
        <>
            <Head>
                <title>Editar persona - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain narrow>
                <PageHeader title="Nova relació UO" back={{ href: "/admin/ougrouprelations", text: "Relacions UO" }} />
                <div className="card p-6 sm:p-8">
                    {showCreated && <div className="mb-5"><SuccessAlert text="Relació creada correctament" /></div>}
                    <form action="#" method="post" onSubmit={onFormSubmit} autoComplete="off">
                        <OuGroupRelationsFields
                            groupSelector={{ selected: ouGroupRelation.groupId === 0 ?  "" : ouGroupRelation.groupId, options: groups.options }}
                            ouGroupRelation={ouGroupRelation}
                            setOuGroupRelation={setOuGroupRelation}
                            errors={updateErrors}
                        />

                        <div>
                            <input
                                disabled={formDisabled()}
                                className="btn btn-primary mt-8 w-full"
                                value="Crear"
                                type="submit" />
                        </div>
                    </form>
                </div>
            </PageMain>
        </>
    )
}

export default function CreateUoGroupRelationPage() {
    return (
        <Container>
            <Create />
        </Container>
    )
};