import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Table } from '@/components/table'
import { Container } from '@/components/layout/SideBar'
import Link from 'next/link'
import { deleteOuGroupRelation, deletePerson, exportPeople, filterPeopleQuery, getOuGroupRelationsView } from '@/lib/apis/payments/client'
import useDebounce from '@/lib/hooks/useDebounce'
import { Spinner } from '@/components/Loading'
import { useApiRequest, useStartApiRequest } from '@/lib/hooks/useApiRequest'
import { displayErrors, plainErrors } from '@/lib/utils'
import { OuGroupRelationRow } from '@/lib/apis/payments'

const tableHeaders = {
    id: "Id",
    groupName: "Nom del grup",
    groupMail: "Correu del grup",
    oldOu: "UO Antiga",
    activeOu: "UO Activa",
    actions: "Accions",
};

interface TableRow extends OuGroupRelationRow {
    actions: string
}

const OuGroupRelations = () => {
    const { data, errors, isLoading, executeRequest } = useStartApiRequest(getOuGroupRelationsView);
    const { errors: deleteErrors, isLoading: deleteLoading, executeRequest: deleteRequest } = useApiRequest(deleteOuGroupRelation);

    useEffect(() => {
        if (!deleteErrors) return;
        alert(plainErrors(deleteErrors));
    }, [deleteErrors])

    const mapToRow = (): TableRow[] => {
        if (!data) return []
        return data.map(x => ({ actions: "", ...x }));
    }

    const onDeleteOuGroupRelation = async (item: TableRow) => {
        if (!confirm(`Segur que vols eliminar l'OU: ${item.groupMail}?`)) return;

        const ok = await deleteRequest(item.id);
        if (ok) {
            executeRequest();
        }
    }

    const customRenderer = {
        actions: (item: TableRow) => {
            return (
                <div className='flex justify-center'>
                    <Link
                        title="Editar"
                        className='font-medium text-blue-600 hover:underline' href={`/admin/people/${item.id}`}>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                        </svg>
                    </Link>

                    <button
                        title="Eliminar"
                        className={`font-medium hover:underline ml-5 ${deleteLoading ? 'text-gray-500' : 'text-red-600'}`}
                        disabled={deleteLoading}
                        onClick={() => onDeleteOuGroupRelation(item)}>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                        </svg>
                    </button>
                </div>
            );
        },
    }

    const listPeople = () => {
        return (
            <>
                <div className='overflow-y-auto overflow-x-auto'>
                    <Table
                        headers={tableHeaders}
                        items={mapToRow()}
                        renderers={customRenderer}
                        tableClass='w-full table-auto overflow-scroll h-full'
                        headerCellClass='text-sm font-medium text-gray-900 px-6 py-4 text-left text-center'
                        cellClass='px-6 py-4 whitespace-nowrap text-center'
                        rowClass='border-b hover:bg-blue-100'
                        visibleFields={[
                            "groupName",
                            "groupMail",
                            "activeOu",
                            "oldOu",
                            "actions"
                        ]}
                    />
                </div>
            </>
        )
    }

    if (isLoading) return null;

    return (
        <>
            <Head>
                <title>Persones - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='mt-5 mx-1 md:mx-4 lg:mx-6'>
                <div className='flex mb-4'>
                    <Link className='
                        text-white 
                        bg-green-700 
                        hover:bg-green-800 
                        focus:ring-4 
                        focus:ring-green-300
                        font-medium
                        py-3
                        px-3
                        rounded-lg
                        text-sm
                        mr-5' href="/admin/people/create">Afegir persona</Link>
                    <Link className='
                        text-white 
                        bg-blue-700 
                        hover:bg-blue-800 
                        focus:ring-4 
                        focus:ring-blue-300
                        font-medium
                        py-3
                        px-3
                        rounded-lg
                        text-sm' href="/admin/tasks/upload">Carregar persones</Link>
                </div>
                {errors ? displayErrors(errors) : listPeople()}
            </main>
        </>
    )
}

export default function OuGroupRelationsPage() {
    return (
        <Container>
            <OuGroupRelations />
        </Container>
    )
};