import { SuccessAlert } from "@/components/Alerts";
import { Group } from "@/lib/apis/payments/models";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { Container } from "@/components/layout/SideBar";
import Head from "next/head";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import { useApiRequest } from "@/lib/hooks/useApiRequest";
import { getGroupById, updateGroup } from "@/lib/apis/payments/client";
import GroupFields from "@/components/groups/GroupFields";

const Update = () => {
    const router = useRouter()
    const { id } = router.query

    const [showUpdated, setShowUpdated] = useState(false);
    const { data: group, isLoading: isGroupLoading, executeRequest: getGroupRequest } = useApiRequest(getGroupById);
    const { errors: updateErrors, isLoading: isUpdateLoading, executeRequest: updateGroupRequest } = useApiRequest(updateGroup);

    useEffect(() => {
        if (!id) return;
        getGroupRequest(parseInt(id as string))
    }, [id]);

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        const form = e.currentTarget;
        const formData = new FormData(form);
        const g: Group = {
            id: parseInt(id as string),
            name: formData.get("name") as string,
            description: formData.get("description") as string,
        };

        const ok = await updateGroupRequest(g);
        if (ok) {
            setShowUpdated(true);
            setTimeout(() => setShowUpdated(false), 1500);
        }
    }





    const formDisabled = () => isUpdateLoading || isGroupLoading;

    if (!group) return null;

    return (
        <>
            <Head>
                <title>Editar grup - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain narrow>
                <PageHeader title="Editar grup" subtitle={group.name} back={{ href: "/admin/groups", text: "Grups" }} />
                <div className="card p-6 sm:p-8">
                        {showUpdated ? <div className="mb-5"><SuccessAlert text="Grup actualitzat correctament" /></div> : null}
                        <form action="#" method="post" onSubmit={onFormSubmit} autoComplete="off">
                            <GroupFields
                                errors={updateErrors}
                                group={group} />

                            <div>
                                <input
                                    disabled={formDisabled()}
                                    className="btn btn-primary mt-8 w-full"
                                    value="Guardar canvis"
                                    type="submit" />
                            </div>
                        </form>
                    </div>
            </PageMain>
        </>
    )
}

export default function UpdateGroupPage() {
    return (
        <Container>
            <Update />
        </Container>
    )
};