import { SuccessAlert } from "@/components/Alerts";
import { createGroup } from "@/lib/apis/payments/client";
import { Group } from "@/lib/apis/payments/models";
import Head from "next/head";
import { Container } from "@/components/layout/SideBar";
import { useApiRequest } from "@/lib/hooks/useApiRequest";
import { useState } from "react";
import GroupFields from "@/components/groups/GroupsFields";

const defaultGroup: Group = {
    id: 0,
    name: "",
    description: "",
};

const Create = () => {
    const [showSuccess, setShowSuccess] = useState(false);
    const { data, errors, isLoading, executeRequest } = useApiRequest(createGroup);

    const submit = async (g: Group) => {
        const ok = await executeRequest(g);
        if (ok) setShowSuccess(true);
    }

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        const form = e.currentTarget;
        const formData = new FormData(form);
        const g: Group = {
            id: 0,
            name: formData.get("name") as string,
            description: formData.get("description") as string,
        };
        submit(g);
    }

    const formDisabled = () => isLoading;

    return (
        <>
            <Head>
                <title>Afegir grup - IES MOSSÈN ALCOVER</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="max-w-lg m-auto">
                    <div className="m-5">
                        {
                            data ? <SuccessAlert text="Grup afegit correctament" /> :
                                <form action="#" method="post" onSubmit={onFormSubmit} autoComplete="off">
                                    <GroupFields
                                        errors={errors}
                                        group={defaultGroup} />
                                    <div>
                                        <input
                                            disabled={formDisabled()}
                                            className="w-full mt-6 bg-blue-500 hover:cursor-pointer hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none disabled:hover:cursor-not-allowed"
                                            value="Afegir grup"
                                            type="submit" />
                                    </div>
                                </form>
                        }
                    </div>
                </div>
            </main>
        </>
    )
}

export default function CreateGroupPage() {
    return (
        <Container>
            <Create />
        </Container>
    )
};