import { SuccessAlert } from "@/components/Alerts";
import { createGroup } from "@/lib/apis/payments/client";
import { Group } from "@/lib/apis/payments/models";
import Head from "next/head";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import { Container } from "@/components/layout/SideBar";
import { useApiRequest } from "@/lib/hooks/useApiRequest";
import GroupFields from "@/components/groups/GroupFields";

const defaultGroup: Group = {
    id: 0,
    name: "",
    description: "",
};

const Create = () => {
    const { data, errors, isLoading, executeRequest } = useApiRequest(createGroup);

    const submit = async (g: Group) => {
        const ok = await executeRequest(g);
    }

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        const form = e.currentTarget;
        const formData = new FormData(form);
        const g: Group = {
            id: 0,
            name: formData.get("name") as string,
            description: formData.get("description") as string,
        };
        submit(g);
    }

    const formDisabled = () => isLoading;

    return (
        <>
            <Head>
                <title>Afegir grup - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain narrow>
                <PageHeader title="Nou grup" back={{ href: "/admin/groups", text: "Grups" }} />
                <div className="card p-6 sm:p-8">
                        {
                            data ? <SuccessAlert text="Grup afegit correctament" /> :
                                <form action="#" method="post" onSubmit={onFormSubmit} autoComplete="off">
                                    <GroupFields
                                        errors={errors}
                                        group={defaultGroup} />
                                    <div>
                                        <input
                                            disabled={formDisabled()}
                                            className="btn btn-primary mt-8 w-full"
                                            value="Afegir grup"
                                            type="submit" />
                                    </div>
                                </form>
                        }
                    </div>
            </PageMain>
        </>
    )
}

export default function CreateGroupPage() {
    return (
        <Container>
            <Create />
        </Container>
    )
};