import { Container } from "@/components/layout/SideBar";
import { Table } from "@/components/table";
import { getGroupsView } from "@/lib/apis/payments";
import Head from "next/head";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import Link from "next/link";
import { useStartApiRequest } from "@/lib/hooks/useApiRequest";

const tableHeaders = {
    id: "Id",
    name: "Nom",
    description: "Descripció",
    actions: "Accions",
};

interface TableRow {
    id: number,
    name: string,
    description: string,
    actions: string,
};

const Groups = () => {

    const { data: groups } = useStartApiRequest(getGroupsView);

    const mapToRow = (): TableRow[] => {
        if (!groups) return [];

        return groups.map(x => {
            return {
                id: x.id,
                name: x.name,
                description: x.description,
                actions: ""
            };
        });
    }

    const customRenderer = {
        name: (item: TableRow) => <span className="font-medium text-slate-900">{item.name}</span>,
        actions: (item: TableRow) => {
            return (
                <div className="flex justify-end gap-1">
                    <Link title="Editar" className='btn-icon' href={`/admin/groups/${item.id}`}>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="h-5 w-5">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                        </svg>
                    </Link>
                </div>
            );
        },
    }



    const listGroups = () => {
        return (
            <div className='card overflow-x-auto'>
                <Table
                    headers={tableHeaders}
                    items={mapToRow()}
                    renderers={customRenderer}
                    tableClass='data-table'
                    visibleFields={[
                        "name",
                        "description",
                        "actions"
                    ]}
                />
            </div>
        )
    }

    return (

        <>
            <Head>
                <title>Grups - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain>
                <PageHeader
                    title="Grups"
                    subtitle="Grups d'alumnes del centre"
                    actions={
                        <Link className='btn btn-primary' href="/admin/groups/create">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="h-4 w-4">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                            </svg>
                            Nou grup
                        </Link>
                    } />

                {listGroups()}
            </PageMain>
        </>
    );
}

export default function GroupsPage() {
    return (
        <Container>
            <Groups />
        </Container>
    )
};