import { Container } from "@/components/layout/SideBar";
import { Table } from "@/components/table";
import { getGroupsView } from "@/lib/apis/payments";
import Head from "next/head";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import Link from "next/link";
import { useApiRequest, useStartApiRequest } from "@/lib/hooks/useApiRequest";
import { deleteGroup } from "@/lib/apis/payments/client";
import { plainErrors } from "@/lib/utils";
import { useEffect } from "react";
import { hasRole, Roles } from "@/lib/apis/payments/models";
import useUser from "@/lib/hooks/useUser";

const tableHeaders = {
    id: "Id",
    name: "Nom",
    description: "Descripció",
    actions: "Accions",
};

interface TableRow {
    id: number,
    name: string,
    description: string,
    actions: string,
};

const Groups = () => {

    const { data: groups, executeRequest } = useStartApiRequest(getGroupsView);
    const { errors: deleteErrors, isLoading: deleteLoading, executeRequest: deleteRequest } = useApiRequest(deleteGroup);
    const { user, loading } = useUser();
    const canEdit = !loading && hasRole(user?.role, Roles.SuperUser);

    useEffect(() => {
        if (!deleteErrors) return;
        alert(plainErrors(deleteErrors));
    }, [deleteErrors])

    const onDeleteGroup = async (item: TableRow) => {
        if (!confirm(`Segur que vols eliminar el grup: ${item.name}?`)) return;

        const ok = await deleteRequest(item.id);
        if (ok) {
            executeRequest();
        }
    }

    const mapToRow = (): TableRow[] => {
        if (!groups) return [];

        return groups.map(x => {
            return {
                id: x.id,
                name: x.name,
                description: x.description,
                actions: ""
            };
        });
    }

    const customRenderer = {
        name: (item: TableRow) => <span className="font-medium text-slate-900">{item.name}</span>,
        actions: (item: TableRow) => {
            return (
                <div className="flex justify-end gap-1">
                    <Link title="Editar" className='btn-icon' href={`/admin/groups/${item.id}`}>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="h-5 w-5">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                        </svg>
                    </Link>
                    <button
                        title="Eliminar"
                        className='btn-icon btn-icon-danger'
                        disabled={deleteLoading}
                        onClick={() => onDeleteGroup(item)}>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="h-5 w-5">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                        </svg>
                    </button>
                </div>
            );
        },
    }



    const listGroups = () => {
        return (
            <div className='card overflow-x-auto'>
                <Table
                    headers={tableHeaders}
                    items={mapToRow()}
                    renderers={customRenderer}
                    tableClass='data-table'
                    visibleFields={canEdit ? [
                        "name",
                        "description",
                        "actions"
                    ] : [
                        "name",
                        "description"
                    ]}
                />
            </div>
        )
    }

    return (

        <>
            <Head>
                <title>Grups - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain>
                <PageHeader
                    title="Grups"
                    subtitle="Grups d'alumnes del centre"
                    actions={canEdit &&
                        <Link className='btn btn-primary' href="/admin/groups/create">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="h-4 w-4">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                            </svg>
                            Nou grup
                        </Link>
                    } />

                {listGroups()}
            </PageMain>
        </>
    );
}

export default function GroupsPage() {
    return (
        <Container>
            <Groups />
        </Container>
    )
};