import { Container } from "@/components/layout/SideBar";
import { Table } from "@/components/table";
import { getGroupsView } from "@/lib/apis/payments";
import Head from "next/head";
import Link from "next/link";
import { useStartApiRequest } from "@/lib/hooks/useApiRequest";

const tableHeaders = {
    id: "Id",
    name: "Nom",
    description: "Descripció",
    actions: "Accions",
};

interface TableRow {
    id: number,
    name: string,
    description: string,
    actions: "",
};

const Groups = () => {

    const { data: groups } = useStartApiRequest(getGroupsView);

    const mapToRow = (): TableRow[] => {
        if (!groups) return [];

        return groups.map(x => {
            return {
                id: x.id,
                name: x.name,
                description: x.description,
                actions: ""
            };
        });
    }

    const customRenderer = {
        actions: (item: TableRow) => {
            return (
                <div className="flex justify-center">
                    <Link title="Editar" className='font-medium text-blue-600 hover:underline ml-5' href={`/admin/groups/${item.id}`}>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="w-6 h-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                        </svg>
                    </Link>
                </div>
            );
        },
    }



    const listGroups = () => {
        return (
            <div className='overflow-x-auto'>
                <Table
                    headers={tableHeaders}
                    items={mapToRow()}
                    renderers={customRenderer}
                    tableClass='w-full table-auto overflow-scroll'
                    headerClass='border-b'
                    headerCellClass='text-sm font-medium text-gray-900 px-6 py-4 text-left text-center'
                    cellClass='px-6 py-4 whitespace-nowrap text-center'
                    rowClass='border-b hover:bg-blue-100'
                    visibleFields={[
                        "name",
                        "description",
                        "actions"
                    ]}
                />
            </div>
        )
    }

    return (

        <>
            <Head>
                <title>Esdeveniments - IES MOSSÈN ALCOVER</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="mt-5 mx-10">


                <div className='flex justify-between mb-4'>
                    <div>
                        <Link className='
                                inline-block
                                text-white 
                                bg-green-700 
                                hover:bg-green-800
                                focus:ring-4 
                                focus:ring-blue-300
                                font-medium
                                py-3
                                px-3
                                rounded-lg
                                text-sm
                                mr-5' href="/admin/groups/create">Nou grup</Link>
                    </div>
                </div>

                {listGroups()}
            </main>
        </>
    );
}

export default function GroupsPage() {
    return (
        <Container>
            <Groups />
        </Container>
    )
};