import { SuccessAlert } from "@/components/Alerts";
import { Course } from "@/lib/apis/payments/models";
import Head from "next/head";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import { Container } from "@/components/layout/SideBar";
import { useApiRequest } from "@/lib/hooks/useApiRequest";
import CourseFields from "@/components/courses/CourseFields";
import { createCourse } from "@/lib/apis/payments";

const defaultCourse: Course = {
    id: 0,
    name: "",
    startDate: "",
    endDate: "",
    active: false,
};

const Create = () => {
    const { data, errors, isLoading, executeRequest } = useApiRequest(createCourse);

    const submit = async (c: Course) => {
        const ok = await executeRequest(c);
    }

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        const form = e.currentTarget;
        const formData = new FormData(form);
        const start = formData.get("startDate") as string;
        const end = formData.get("endDate") as string;
        const c: Course = {
            id: 0,
            name: formData.get("name") as string,
            startDate: start ? new Date(start).toJSON() : undefined,
            endDate: end ? new Date(end).toJSON() : undefined,
            active: false,
        };
        submit(c);
    }

    const formDisabled = () => isLoading;

    return (
        <>
            <Head>
                <title>Afegir curs - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain narrow>
                <PageHeader title="Nou curs" back={{ href: "/admin/courses", text: "Cursos" }} />
                <div className="card p-6 sm:p-8">
                        {
                            data ? <SuccessAlert text="Curs afegit correctament" /> :
                                <form action="#" method="post" onSubmit={onFormSubmit} autoComplete="off">
                                    <CourseFields
                                        errors={errors}
                                        course={defaultCourse} />
                                    <div>
                                        <input
                                            disabled={formDisabled()}
                                            className="btn btn-primary mt-8 w-full"
                                            value="Afegir curs"
                                            type="submit" />
                                    </div>
                                </form>
                        }
                    </div>
            </PageMain>
        </>
    )
}

export default function CreateCoursePage() {
    return (
        <Container>
            <Create />
        </Container>
    )
};