import { Container } from "@/components/layout/SideBar";
import { Table } from "@/components/table";
import { getCourses, setActiveCourse } from "@/lib/apis/payments";
import Head from "next/head";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import Link from "next/link";
import { useApiRequest, useStartApiRequest } from "@/lib/hooks/useApiRequest";
import { displayDate, plainErrors } from "@/lib/utils";

const tableHeaders = {
    id: "Id",
    name: "Nom",
    startDate: "Inici",
    endDate: "Fi",
    active: "Actiu",
    activeText: "Actiu",
    actions: "Accions"
};

interface TableRow {
    id: number,
    name: string,
    startDate: string,
    endDate: string,
    active: boolean,
    activeText: string,
    actions: string,
};

const Courses = () => {

    const { data: courses, executeRequest: getCoursesRequest } = useStartApiRequest(getCourses);
    const { errors: setActiveErrors, executeRequest: setActiveRequest } = useApiRequest(setActiveCourse);

    const mapToRow = (): TableRow[] => {
        if (!courses) return [];

        return courses.map(x => {
            return {
                id: x.id,
                name: x.name,
                active: x.active,
                activeText: x.active ? "Sí" : "No",
                startDate: x.startDate ? displayDate(x.startDate) : "",
                endDate: x.endDate ? displayDate(x.endDate) : "",
                actions: ""
            };
        });
    }

    const onActiveCourse = async (id: number) => {
        const ok = await setActiveRequest(id);
        if (ok) await getCoursesRequest();
    }

    const customRenderer = {
        name: (item: TableRow) => <span className="font-medium text-slate-900">{item.name}</span>,
        activeText: (item: TableRow) => (
            <span className={`badge ${item.active ? "badge-green" : "badge-gray"}`}>
                {item.active && <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />}
                {item.activeText}
            </span>
        ),
        actions: (item: TableRow) => {

            const renderSetActive = () => {
                if (item.active) return null;


                return (
                    <button className='btn-icon' title="Activar curs" onClick={() => onActiveCourse(item.id)}>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M5.25 5.653c0-.856.917-1.398 1.667-.986l11.54 6.348a1.125 1.125 0 010 1.971l-11.54 6.347a1.125 1.125 0 01-1.667-.985V5.653z" />
                        </svg>
                    </button>
                );
            }

            return (
                <div className="flex justify-end gap-1">
                    <Link title="Editar" className='btn-icon' href={`/admin/courses/${item.id}`}>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor" className="h-5 w-5">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                        </svg>
                    </Link>

                    {renderSetActive()}

                </div>
            );
        },
    }



    const listCourses = () => {
        return (
            <>
                {setActiveErrors ? <p className="form-error mb-4">{plainErrors(setActiveErrors)}</p> : null}
                <div className='card overflow-x-auto'>
                <Table
                    headers={tableHeaders}
                    items={mapToRow()}
                    renderers={customRenderer}
                    tableClass='data-table'
                    visibleFields={[
                        "name",
                        "startDate",
                        "endDate",
                        "activeText",
                        "actions"
                    ]}
                />
                </div>
            </>
        )
    }

    return (

        <>
            <Head>
                <title>Cursos - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain>
                <PageHeader
                    title="Cursos"
                    subtitle="Cursos acadèmics i curs actiu"
                    actions={
                        <Link className='btn btn-primary' href="/admin/courses/create">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="h-4 w-4">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                            </svg>
                            Nou curs
                        </Link>
                    } />

                {listCourses()}
            </PageMain>
        </>
    );
}

export default function GroupsPage() {
    return (
        <Container>
            <Courses />
        </Container>
    )
};