import { Container } from "@/components/layout/SideBar";
import { EventPayments } from "@/lib/apis/payments";
import { getEventPayments, setPayment } from "@/lib/apis/payments/client";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const EventPayments = () => {
    const router = useRouter()
    const [data, setData] = useState<EventPayments | undefined>(undefined)

    const { id } = router.query

    const loadEventsPayments = () => {
        getEventPayments(id as string)
            .then(x => {
                if (x.errors) {
                    console.log(x.errors);
                } else {
                    setData(x.data);
                }
            })
    }

    useEffect(() => {
        loadEventsPayments();
    }, [id])

    if (!data) return null;

    
    const payment = async (id: number, v: boolean) => {
        const result = await setPayment(id, v);

        if (!result.errors) {
            loadEventsPayments();
        } else {
            alert("No s'ha pogut actualitzar")
        }
    }

    const paidEvents = data.paidEvents.map(x => (
        <li key={x.id} className="mt-3 relative">
            <hr className="h-px mt-1 mb-1 bg-gray-200 border-0"></hr>
            {x.group} - {x.documentId} - {x.fullName}
            <button onClick={() => payment(x.id, false)} className="absolute inset-y-0 right-0 text-red-600 font-bold">Desmarcar Pagat</button>
        </li>
    ))

    const unPaidEvents = data.unPaidEvents.map(x => (
        <li key={x.id} className="mt-3 relative">
            <hr className="h-px mt-1 mb-1 bg-gray-200 border-0"></hr>
            {x.group} - {x.documentId} - {x.fullName}
            <button onClick={() => payment(x.id, true)} className="absolute inset-y-0 right-0 text-green-600 font-bold">Marcar Pagat</button>
        </li>
    ))


    const summaryURL = () => `${window.location.protocol}//${window.location.hostname}/admin/events/${data.code}/summary`;

    const copyToClipboard = () => {
        navigator.clipboard.writeText(summaryURL());
        alert("Copiat al porta-retalls");
    }

    

    return (

        <>
            <Head>
                <title>Pagaments esdeveniment - IES MOSSÈN ALCOVER</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="p-10">
                <div className="flex justify-between items-center">
                    <div className="flex items-baseline">
                        <h4 className="font-bold text-3xl">{data.code}</h4>
                        <h4 className="font-bold text-3xl ml-3">-</h4>
                        <h4 className="font-bold text-3xl ml-3">{data.name}</h4>
                    </div>
                    <div className="flex">
                        <button
                            className="text-blue-600 font-bold pr-2"
                            onClick={copyToClipboard}>Copiar - </button>
                        <Link href={summaryURL()} target="_blank">{summaryURL()}</Link>
                    </div>
                </div>
                <h4 className="mt-3 font-semibold">Total: {data.totalPrice} €</h4>
                <h4 className="mt-3 font-semibold">Amipa total: {data.amipaTotalPrice} €</h4>
                <h4 className="mt-3 font-semibold">No Amipa total: {data.noAmipaTotalPrice} €</h4>
                <hr className="h-px mt-3 mb-8 bg-gray-500 border-0" />
                <h4 className="mt-3 font-semibold">Alumnes total: {data.count}</h4>
                <h4 className="mt-3 font-semibold">Alumnes Amipa: {data.amipaStudents}</h4>
                <h4 className="mt-3 font-semibold">Alumnes No Amipa: {data.noAmipaStudents}</h4>
                <hr className="h-px mt-3 mb-8 bg-gray-500 border-0" />
                <h3 className="text-green-700 text-lg font-bold">Pagats: {data.paidCount}</h3>
                <ul>
                    {paidEvents}
                </ul>
                <hr className="h-px mt-3 mb-8 bg-white-300 border-0" />
                <h3 className="text-red-500 text-lg font-bold">No Pagats: {data.count - data.paidCount}</h3>
                <ul>
                    {unPaidEvents}
                </ul>
            </main>
        </>
    );
}

export default function EventPaymentsPage() {



    return (
        <Container>
            <EventPayments />
        </Container>
    )
};