import { Container } from "@/components/layout/SideBar";
import { EventPayments, getEventPayments, setPayment } from "@/lib/apis/payments";
import Head from "next/head";
import Link from "next/link";
import { Table } from "@/components/table";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";


const tableHeaders = {
    id: "",
    personesTotal: "Recompte Total",
    personesActual: "Recompte Actual",
    dinersTotal: "Diners Totals",
    dinersActual: "Diners Actuals"
};

interface TableRow {
    id: string,
    personesTotal: string,
    personesActual: string,
    dinersTotal: string,
    dinersActual: string
};

const EventPayments = () => {
    const router = useRouter()
    const [data, setData] = useState<EventPayments | undefined>(undefined)

    const { id } = router.query

    const getItems = () => {
        if (!data) return [];
        return [
            {
              id: "No Amipa",
              personesTotal: data.summary.noAmipaCount,
              personesActual: data.summary.paidCount,
              dinersTotal: data.summary.noAmipa  + " €",
              dinersActual: data.summary.noAmipaPaid  + " €"
            },
            {
                id: "Amipa",
                personesTotal: data.summary.amipaCount,
                personesActual: data.summary.amipaPaidCount,
                dinersTotal: data.summary.amipa  + " €",
                dinersActual: data.summary.amipaPaid  + " €"
            },
            {
                id: "Total",
                personesTotal: data.summary.totalCount,
                personesActual: data.summary.totalPaidCount,
                dinersTotal: data.summary.total + " €",
                dinersActual: data.summary.totalPaid  + " €"
            }
          ];
    }


      const mapToRow = (): TableRow[] => {
        return getItems().map(x => ({
          id: x.id,
          personesTotal: x.personesTotal.toString() || '',
          personesActual: x.personesActual.toString() || '',
          dinersTotal: x.dinersTotal.toString() || '',
          dinersActual: x.dinersActual.toString() || '',
        }));
      };

    const loadEventsPayments = () => {
        getEventPayments(id as string)
            .then(x => {
                if (x.errors) {
                    console.log(x.errors);
                } else {
                    setData(x.data);
                }
            })
    }

    useEffect(() => {
        loadEventsPayments();
    }, [id])

    if (!data) return null;

    
    const payment = async (id: number, v: boolean) => {
        const result = await setPayment(id, v);

        if (!result.errors) {
            loadEventsPayments();
        } else {
            alert("No s'ha pogut actualitzar")
        }
    }

    const paidEvents = data.paidEvents.map(x => (
        <li key={x.id} className="mt-3 relative">
            <hr className="h-px mt-1 mb-1 bg-gray-200 border-0"></hr>
            {x.group} - {x.documentId} - {x.fullName}
            <button onClick={() => payment(x.id, false)} className="absolute inset-y-0 right-0 text-red-600 font-bold">Desmarcar Pagat</button>
        </li>
    ))

    const unPaidEvents = data.unPaidEvents.map(x => (
        <li key={x.id} className="mt-3 relative">
            <hr className="h-px mt-1 mb-1 bg-gray-200 border-0"></hr>
            {x.group} - {x.documentId} - {x.fullName}
            <button onClick={() => payment(x.id, true)} className="absolute inset-y-0 right-0 text-green-600 font-bold">Marcar Pagat</button>
        </li>
    ))


    const summaryURL = () => `${window.location.protocol}//${window.location.hostname}/admin/events/${data.code}/summary`;

    const copyToClipboard = () => {
        navigator.clipboard.writeText(summaryURL());
        alert("Copiat al porta-retalls");
    }

    

    return (

        <>
            <Head>
                <title>Pagaments esdeveniment - IES MOSSÈN ALCOVER</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="p-10">
                <div className="flex justify-between items-center">
                    <div className="flex items-baseline">
                        <h4 className="font-bold text-3xl">{data.code}</h4>
                        <h4 className="font-bold text-3xl ml-3">-</h4>
                        <h4 className="font-bold text-3xl ml-3">{data.name}</h4>
                    </div>
                    <div className="flex">
                        <button
                            className="text-blue-600 font-bold pr-2"
                            onClick={copyToClipboard}>Copiar - </button>
                        <Link href={summaryURL()} target="_blank">{summaryURL()}</Link>
                    </div>
                </div>

                <hr className="h-px mt-3 mb-3 bg-gray-500 border-0" />
                <Table
                headers={tableHeaders}
                items={mapToRow()}
                tableClass='min-w-full'
                headerClass='border-b'
                headerCellClass='text-sm font-medium text-gray-900 px-6 py-4 text-left'
                cellClass='text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap'
                rowClass='border-b'
                />

                <h3 className=" mt-8 text-green-700 text-lg font-bold">Pagats: {data.summary.totalPaidCount}</h3>
                <ul>
                    {paidEvents}
                </ul>
                <hr className="h-px mt-3 mb-8 bg-white-300 border-0" />
                <h3 className="text-red-500 text-lg font-bold">No Pagats: {data.summary.totalCount - data.summary.totalPaidCount}</h3>
                <ul>
                    {unPaidEvents}
                </ul>
            </main>
        </>
    );
}

export default function EventPaymentsPage() {



    return (
        <Container>
            <EventPayments />
        </Container>
    )
};