import { Container } from "@/components/layout/SideBar";
import Head from "next/head";

const PeopleToEvent = () => {

    
    return (

        <>
            <Head>
                <title>Events</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                sdadasd
            </main>
        </>
    );
}

export default function PeopleToEventPage() {
    return (
        <Container>
            <PeopleToEvent />
        </Container>
    )
};