import { SuccessAlert } from "@/components/Alerts";
import { createPerson } from "@/lib/apis/payments/client";
import { Person } from "@/lib/apis/payments/models";
import PersonFields from "@/components/people/PersonFields";
import Head from "next/head";
import { Container } from "@/components/layout/SideBar";
import { useApiRequest } from "@/lib/hooks/useApiRequest";
import Link from "next/link";
import { useState } from "react";

const defaultPerson: Person = {
    id: 0,
    name: "",
    surname1: "",
    documentId: "",
    groupId: undefined,
    amipa: false,
    enrolled: false,
};

const Create = () => {
    const [person, setPerson] = useState(defaultPerson);
    const { data, errors, isLoading, executeRequest } = useApiRequest(createPerson);

    const submit = async (p: Person) => {
        await executeRequest(p);
    }

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        if (!person) return;
        submit(person);
    }

    const formDisabled = () => isLoading;

    return (
        <>
            <Head>
                <title>Afegir persona - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="max-w-lg m-auto">
                    <div className="my-5 mx-1 md:mx-4 lg:mx-6">
                        {
                            data ?
                                <SuccessAlert text="Persona afegida correctament">
                                    <Link
                                        className="inline-block font-bold underline mt-3"
                                        href={`/admin/people/${data}`}>{`Editar la persona creada`}</Link>
                                </SuccessAlert> :
                                <form action="#" method="post" onSubmit={onFormSubmit} autoComplete="off">
                                    <PersonFields
                                        errors={errors}
                                        person={person}
                                        setPerson={setPerson} />
                                    <div>
                                        <input
                                            disabled={formDisabled()}
                                            className="w-full mt-6 bg-green-700 hover:cursor-pointer hover:bg-green-800 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none disabled:hover:cursor-not-allowed"
                                            value="Afegir persona"
                                            type="submit" />
                                    </div>
                                </form>
                        }
                    </div>
                </div>
            </main>
        </>
    )
}

export default function CreatePersonPage() {
    return (
        <Container>
            <Create />
        </Container>
    )
};