import { SuccessAlert } from "@/components/Alerts";
import { createPerson } from "@/lib/apis/payments/client";
import { Person } from "@/lib/apis/payments/models";
import PersonFields from "@/components/people/PersonFields";
import Head from "next/head";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import { Container } from "@/components/layout/SideBar";
import { useApiRequest } from "@/lib/hooks/useApiRequest";
import Link from "next/link";
import { useState } from "react";

const defaultPerson: Person = {
    id: 0,
    name: "",
    surname1: "",
    documentId: "",
    groupId: undefined,
    amipa: false,
    enrolled: false,
};

const Create = () => {
    const [person, setPerson] = useState(defaultPerson);
    const { data, errors, isLoading, executeRequest } = useApiRequest(createPerson);

    const submit = async (p: Person) => {
        await executeRequest(p);
    }

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        if (!person) return;
        submit(person);
    }

    const formDisabled = () => isLoading;

    return (
        <>
            <Head>
                <title>Afegir persona - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain narrow>
                <PageHeader title="Afegir persona" back={{ href: "/admin/people", text: "Persones" }} />
                <div className="card p-6 sm:p-8">
                        {
                            data ?
                                <SuccessAlert text="Persona afegida correctament">
                                    <Link
                                        className="link mt-2 inline-block text-emerald-800"
                                        href={`/admin/people/${data}`}>{`Editar la persona creada`}</Link>
                                </SuccessAlert> :
                                <form action="#" method="post" onSubmit={onFormSubmit} autoComplete="off">
                                    <PersonFields
                                        errors={errors}
                                        person={person}
                                        setPerson={setPerson} />
                                    <div>
                                        <input
                                            disabled={formDisabled()}
                                            className="btn btn-primary mt-8 w-full"
                                            value="Afegir persona"
                                            type="submit" />
                                    </div>
                                </form>
                        }
                    </div>
            </PageMain>
        </>
    )
}

export default function CreatePersonPage() {
    return (
        <Container>
            <Create />
        </Container>
    )
};