import Head from 'next/head'
import { useEffect, useState } from 'react'
import { getCoursesSelector, getPeopleView, PersonRow } from '@/lib/apis/payments'
import { Selector, SelectorComponent } from '@/components/Selector'
import { Spinner } from '@/components/Loading'
import { Table } from '@/components/table'

const tableHeaders = {
    id: "Identitat",
    firstName: "Nom",
    lastName: "Llinatges",
    academicRecordNumber: "Número expedien",
    group: "Grup"
};

interface TableRow {
    id: number,
    firstName: string,
    lastName: string,
    academicRecordNumber: string,
    group: string,
};

const People = () => {

    const [loadingCourses, setLoadingCourses] = useState(true)
    const [loadingPeople, setLoadingPeople] = useState(false)
    const [selector, setSelector] = useState<Selector | undefined>(undefined)
    const [people, setPeople] = useState<PersonRow[]>([])
    const [currentCourseId, setCurrentCourseId] = useState<number | undefined>()

    const onCourseSelected = (value: string) => {
        setLoadingPeople(true);
        setCurrentCourseId(parseInt(value))
    }

    const mapToRow = (): TableRow[] => {
        return people.map(x => {
            const academicRecordNumber = x.academicRecordNumber ? x.academicRecordNumber.toString() : "-";
            return { id: x.id, firstName: x.firstName, lastName: x.lastName, academicRecordNumber: academicRecordNumber, group: x.groupName };
        });
    }

    useEffect(() => {
        getCoursesSelector()
            .then(x => setSelector(x))
            .finally(() => setLoadingCourses(false))
    }, []);

    useEffect(() => {
        setLoadingPeople(true);
        getPeopleView(currentCourseId)
            .then(x => setPeople(x))
            .finally(() => setLoadingPeople(false));
    }, [currentCourseId]);

    if (loadingCourses) {
        return null
    }

    const listPeople = () => {
        if (loadingPeople) return null;

        return (
            <Table
                headers={tableHeaders}
                items={mapToRow()}
                tableClass='min-w-full'
                headerClass='border-b'
                headerCellClass='text-sm font-medium text-gray-900 px-6 py-4 text-left'
                cellClass='text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap'
                rowClass='border-b'
            />
        )
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className='flex justify-start items-center mb-4'>
                    <SelectorComponent
                        id='course'
                        name='course'
                        onSelect={onCourseSelected}
                        selector={selector as Selector} />

                    {loadingPeople ? <Spinner /> : null}
                </div>

                {listPeople()}
            </main>
        </>
    )
}


export default People