import Head from 'next/head'
import { useEffect, useRef, useState } from 'react';
import { createOrder, getPersonActiveEvents, PaymentMethod, PersonActiveEvent, PersonActiveEventsVm } from '@/lib/apis/payments';
import { CreateOrderResponse } from '@/lib/apis/payments/models';
import { displayDate } from '@/lib/utils';
import { SelectorComponent } from '@/components/Selector';
import { Spinner } from '@/components/Loading';
import { PublicLayout } from '@/components/layout/PublicLayout';

const Home = () => {

    const [step, setStep] = useState(1)
    const [viewModel, setViewModel] = useState<PersonActiveEventsVm | undefined>(undefined);

    const onEventsLoaded = (data: PersonActiveEventsVm) => {
        setStep(2);
        setViewModel(data);
    }

    return (
        <>
            <Head>
                <title>{`Pagaments - ${process.env.SCHOOL_NAME}`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PublicLayout
                title="Portal de pagaments"
                subtitle={step === 1
                    ? "Consulta i paga els esdeveniments pendents de manera ràpida i segura."
                    : "Selecciona què vols pagar i tria el mètode de pagament."}>
                <Steps current={step} />
                {step === 1 ? <FirstStep onLoaded={onEventsLoaded} /> : null}
                {step === 2 && viewModel ? <SecondStep data={viewModel} /> : null}
            </PublicLayout>
        </>
    )
}

export default Home

const Steps = ({ current }: { current: number }) => {
    const steps = ["Identificació", "Selecció", "Pagament"];

    return (
        <ol className="mb-4 flex items-center gap-2 text-sm">
            {steps.map((x, idx) => {
                const n = idx + 1;
                const done = n < current;
                const active = n === current;
                return (
                    <li key={x} className="flex items-center gap-2">
                        <span className={`flex h-6 w-6 items-center justify-center rounded-full text-xs font-semibold ${active || done ? "bg-white text-brand-700 shadow" : "bg-white/20 text-white"}`}>
                            {done ?
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={3} stroke="currentColor" className="h-3.5 w-3.5">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                                </svg> : n}
                        </span>
                        <span className={`hidden sm:inline ${active ? "font-semibold text-white" : "text-brand-100"}`}>{x}</span>
                        {n < steps.length && <span className="mx-1 h-px w-6 bg-white/30 sm:w-10" />}
                    </li>
                )
            })}
        </ol>
    )
}


interface FirstStepProps {
    onLoaded: (data: PersonActiveEventsVm) => void,
}

const FirstStep = ({ onLoaded }: FirstStepProps) => {

    const [loading, setLoading] = useState(false);
    const [errors, setErrors] = useState<Map<string, string[]>>()

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        setLoading(true);
        const form = e.currentTarget;
        const formData = new FormData(form);
        const documentId = formData.get("documentId") as string;
        const response = await getPersonActiveEvents(documentId);
        if (response.errors) {
            setErrors(response.errors)
            setLoading(false);
        } else if (response.data) {
            onLoaded(response.data);
        }
    }

    const displayErrors = (key: string) => {
        if (!errors || !errors.has(key)) return null;

        const list = errors.get(key) as string[];
        return (
            <>
                {list.map((x, idx) => <p key={idx} className="form-error">{x}</p>)}
            </>
        )
    }

    return (
        <form className='card animate-fade-in p-6 sm:p-8' action="#" onSubmit={onFormSubmit}>
            <div>
                <label
                    className="form-label text-base"
                    htmlFor="documentId">Document d&apos;identitat</label>

                <div className="relative">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="pointer-events-none absolute left-3.5 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M15 9h3.75M15 12h3.75M15 15h3.75M4.5 19.5h15a2.25 2.25 0 002.25-2.25V6.75A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25v10.5A2.25 2.25 0 004.5 19.5zm6-10.125a1.875 1.875 0 11-3.75 0 1.875 1.875 0 013.75 0zm1.294 6.336a6.721 6.721 0 01-3.17.789 6.721 6.721 0 01-3.168-.789 3.376 3.376 0 016.338 0z" />
                    </svg>
                    <input
                        required={true}
                        autoFocus
                        autoComplete="off"
                        placeholder="12345678A"
                        className={`form-input py-3.5 pl-11 text-lg uppercase placeholder:normal-case ${errors ? "ring-red-300 focus:ring-red-500" : ""}`}
                        id="documentId" name="documentId" defaultValue={""} onChange={() => setErrors(undefined)} />
                </div>
                {displayErrors("")}
            </div>

            <p className='form-hint'>
                Per exemple, el document d&apos;identitat de l&apos;alumne.
            </p>

            <button
                disabled={loading}
                className="btn btn-primary btn-lg mt-6 w-full"
                type="submit">
                {loading ? <><Spinner className="h-5 w-5 text-white" />Cercant...</> :
                    <>
                        Continua
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="h-5 w-5">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                        </svg>
                    </>
                }
            </button>
        </form>
    )
}

interface Item {
    event: PersonActiveEvent,
    selected: boolean,
    quantity: number
}


interface SecondStepProps {
    data: PersonActiveEventsVm
}

const SecondStep = ({ data }: SecondStepProps) => {
    const { events, person } = data;
    const [loading, setLoading] = useState(false);

    const [eventItems, setEventItems] = useState<Item[]>(events.map(x => ({ event: x, quantity: 0, selected: false })));

    const [errors, setErrors] = useState<Map<string, string[]>>();
    const [paymentForm, setPaymentForm] = useState<CreateOrderResponse | undefined>(undefined);
    const [paymentMethod, setPaymentMethod] = useState<PaymentMethod | undefined>(undefined);
    const [displayEnrollment, setDisplayEnrollment] = useState(false)
    const formRef = useRef<HTMLFormElement>(null);

    useEffect(() => {
        if (paymentForm && formRef.current) {
            formRef.current.submit();
        }
    }, [paymentForm]);

    const setEventItem = (idx: number, eventItem: Item) => {
        eventItems[idx] = eventItem;
        setEventItems([...eventItems]);
    }

    const getSelectedEvents = () => eventItems.filter(x => x.selected);

    const handlePayClick = async (paymentMethod: PaymentMethod) => {
        setPaymentMethod(paymentMethod);
        setLoading(true);
        const selectedEvents = getSelectedEvents();
        const cmd = {
            documentId: person.documentId,
            paymentMethod,
            events: selectedEvents.map(x => (
                {
                    code: x.event.code,
                    quantity: x.event.displayQuantitySelector ? x.quantity : undefined
                }
            ))
        };
        const response = await createOrder(cmd);
        if (response.errors) {
            setErrors(response.errors)
        } else {
            setPaymentForm(response.data);
        }
    }

    const renderAndSubmitPaymentForm = () => {
        if (!paymentForm) return null;

        return (
            <form id='forma' method='post' action={paymentForm.url} ref={formRef} target="_top">
                <input type="hidden" name="Ds_SignatureVersion" defaultValue={paymentForm.signatureVersion} />
                <input type="hidden" name="Ds_MerchantParameters" defaultValue={paymentForm.merchantParameters} />
                <input type="hidden" name="Ds_Signature" defaultValue={paymentForm.signature} />
            </form>
        )
    }

    const displayErrors = (key: string) => {
        if (!errors || !errors.has(key)) return null;

        const list = errors.get(key) as string[];
        return (
            <>
                {list.map((x, idx) => <p key={idx} className="form-error">{x}</p>)}
            </>
        )
    }

    const spinner = <Spinner className="h-5 w-5 text-white" />;

    const bizumLogo = (
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 122 36" className="h-5 w-auto" fill="none">
            <path fillRule="evenodd" clipRule="evenodd" d="M59.8625 12.8257c-1.0347 0-1.8704.8358-1.8704 1.8308v13.8113c0 1.0348.8357 1.8707 1.8704 1.8707s1.8704-.8359 1.8704-1.8707V14.6565c0-.995-.8357-1.8308-1.8704-1.8308Zm-.0001-6.88561c-1.154 0-2.1091.95524-2.1091 2.1095 0 1.15425.9551 2.14931 2.1091 2.14931 1.1541 0 2.1092-.95526 2.1092-2.14931 0-1.15426-.9551-2.1095-2.1092-2.1095ZM78.089 14.6566c0-1.1543-.9153-1.5921-1.751-1.5921h-9.2725c-.9153 0-1.6316.7164-1.6316 1.5921 0 .9154.7163 1.6319 1.6316 1.6319h6.0888l-7.8796 10.9853c-.2388.3184-.3581.7562-.3581 1.1144 0 1.1543.9153 1.7911 1.7112 1.7911h9.8296c.9153 0 1.6316-.7164 1.6316-1.6319 0-.9154-.7163-1.6318-1.6316-1.6318h-6.6062l7.7204-10.7466c.398-.5572.5174-1.0348.5174-1.5124Zm-27.3 8.6769c0 2.2687-.9949 3.6618-3.2633 3.6618-2.2683 0-3.2234-1.3931-3.2234-3.6618v-7.045h3.3826c2.7459 0 3.1041 1.5125 3.1041 3.1842v3.8608Zm3.7408-3.9404c0-3.8608-2.0296-6.3683-6.7653-6.3683h-3.4224V7.81078c0-1.03485-.8357-1.87069-1.8306-1.87069-1.0347 0-1.8704.83584-1.8704 1.87069V23.3335c0 3.8608 2.0693 7.0051 6.9642 7.0051 4.8551 0 6.9643-3.1841 6.9643-7.0051v-3.9404h-.0398Zm38.1642-6.5674c-1.0346 0-1.8704.8358-1.8704 1.8706v8.6371c0 2.2687-.9949 3.6617-3.2632 3.6617-2.2684 0-3.2235-1.393-3.2235-3.6617v-8.6371c0-1.0348-.8357-1.8706-1.8306-1.8706-1.0347 0-1.8704.8358-1.8704 1.8706v8.6371c0 3.8607 2.0694 7.0051 6.9643 7.0051 4.8551 0 6.9642-3.1842 6.9642-7.0051v-8.6371c-.0397-1.0348-.8755-1.8706-1.8704-1.8706Zm28.374 7.0451c0-3.8608-1.79-7.0052-6.645-7.0052-2.189 0-3.741.6369-4.816 1.7115-1.074-1.0348-2.626-1.7115-4.815-1.7115-4.8552 0-6.646 3.1842-6.646 7.0052v8.637c0 1.0348.8357 1.8707 1.8306 1.8707 1.0344 0 1.8704-.8359 1.8704-1.8707v-8.637c0-2.2687.716-3.6618 2.945-3.6618 2.268 0 2.945 1.3931 2.945 3.6618v8.637c0 1.0348.836 1.8707 1.83 1.8707 1.035 0 1.871-.8359 1.871-1.8707v-8.637c0-2.2687.716-3.6618 2.945-3.6618 2.268 0 2.945 1.3931 2.945 3.6618v8.637c0 1.0348.835 1.8707 1.83 1.8707 1.035 0 1.871-.8359 1.871-1.8707l.039-8.637ZM6.61567 12.8655c1.31327.9553 3.14387.6767 4.09893-.6368l3.4225-4.73643c.9551-1.31346.6765-3.14434-.6367-4.09959-1.3133-.95524-3.1439-.67663-4.09902.63683L5.93914 8.76593c-.9153 1.31347-.63673 3.14437.67653 4.09957ZM22.2952 6.17881c-1.3133-.95524-3.1439-.67663-4.099.63683L4.42685 25.7613c-.9551 1.3135-.67653 3.1444.63673 4.0996 1.31326.9553 3.14387.6767 4.09897-.6368L22.9319 10.2784c.9949-1.31345.6765-3.14434-.6367-4.09959ZM5.3024 4.66637c.9551-1.31346.67652-3.14435-.63674-4.099591C3.3524-.388466 1.52179-.109853.566693 1.20361c-.9551 1.31346-.676529 3.14435.636737 4.09959 1.31326.95525 3.14387.67663 4.09897-.63683ZM26.1952 30.6968c-1.3132-.9553-3.1438-.6766-4.0989.6368-.9551 1.3135-.6766 3.1444.6367 4.0996 1.3133.9553 3.1439.6766 4.099-.6368.9551-1.3135.6765-3.1444-.6368-4.0996Zm-5.3724-7.5226c-1.3132-.9552-3.1438-.6766-4.0989.6369l-3.4623 4.7364c-.9551 1.3134-.6765 3.1443.6367 4.0996 1.3133.9552 3.1439.6766 4.099-.6369l3.4623-4.7364c.9551-1.3134.6765-3.1443-.6368-4.0996Z" fill="white" />
        </svg>
    );

    const displayPayButton = () => {
        return (
            <>
                {displayErrors("eventCodes")}
                <div className='mt-5 grid gap-3 sm:grid-cols-2'>
                    <button disabled={loading}
                        onClick={() => handlePayClick(PaymentMethod.Card)}
                        type="button"
                        className="btn btn-primary btn-lg w-full">
                        {loading && paymentMethod === PaymentMethod.Card ? <>{spinner}Carregant...</> :
                            <>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.8} stroke="currentColor" className="h-5 w-5">
                                    <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 002.25-2.25V6.75A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25v10.5A2.25 2.25 0 004.5 19.5z" />
                                </svg>
                                Pagar amb targeta
                            </>}
                    </button>
                    <button disabled={loading}
                        onClick={() => handlePayClick(PaymentMethod.Bizum)}
                        type="button"
                        className="btn btn-lg w-full bg-cyan-600 text-white hover:bg-cyan-700 focus-visible:ring-cyan-500 disabled:hover:bg-cyan-600">
                        {loading && paymentMethod === PaymentMethod.Bizum ? <>{spinner}Carregant...</> : <>Pagar amb {bizumLogo}</>}
                    </button>
                </div>
                <p className="mt-4 flex items-center justify-center gap-1.5 text-xs text-slate-400">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.8} stroke="currentColor" className="h-4 w-4">
                        <path strokeLinecap="round" strokeLinejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
                    </svg>
                    Seràs redirigit a la passarel·la de pagament segura del banc.
                </p>
            </>
        )
    }

    const displayTotal = () => {
        const selectedEvents = getSelectedEvents();

        if (selectedEvents.length === 0) {
            return null
        }

        let total = selectedEvents.reduce((part, x) => part + x.event.price * Math.max(x.quantity, 1), 0);

        return (
            <div className="animate-fade-in border-t border-slate-200 bg-slate-50/80 p-6 sm:px-8">
                <div className='flex items-baseline justify-between'>
                    <span className="text-slate-600">
                        Total <span className="text-sm text-slate-400">({selectedEvents.length} {selectedEvents.length === 1 ? "element" : "elements"})</span>
                    </span>
                    <span className='text-3xl font-bold tracking-tight text-slate-900 tabular-nums'>{total} {events[0].currencySymbol}</span>
                </div>
                {displayPayButton()}
            </div>
        )
    }

    const displayEvents = () => {
        if (!events || events.length == 0) {
            return (
                <div className="px-6 py-12 text-center sm:px-8">
                    <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-50 text-emerald-600">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="h-6 w-6">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                        </svg>
                    </div>
                    <h2 className='mt-4 font-semibold text-slate-900'>
                        No hi ha esdeveniments actius pendents de pagar.
                    </h2>
                    {/* {amipaMessage()} */}
                </div>
            )
        }

        return (
            <div className="p-6 sm:px-8">
                <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-slate-500">Selecciona els esdeveniments a pagar</h2>
                <ul className="space-y-3">
                    {eventItems.map((x, idx) =>
                        <li key={x.event.code}
                            className={`rounded-xl p-4 ring-1 transition-all ${x.selected
                                ? "bg-brand-50/60 ring-2 ring-brand-500"
                                : "bg-white ring-slate-200 hover:ring-slate-300"} ${x.event.selectable ? "" : "opacity-60"}`}>
                            <EventLine
                                item={x}
                                idx={idx}
                                setEventItem={setEventItem} />
                        </li>
                    )}
                </ul>
                {/* {amipaMessage()} */}
            </div>
        )
    }

    const amipaMessage = () => {
        return (
            <div>
                <a target='blank' href='https://drive.google.com/file/d/1811V-ydbXgL_r0zCrsm3qVDyjypDqtrG/view?usp=sharing'
                    className='link md:text-lg'>
                    Per fer-te soci d&apos;AMIPA clica aquí
                </a>
            </div>
        )
    }

    const enrollmentButton = !person.enrolled || !person.enrollmentSubjectsInfo ? null :
        (
            <>
                <button
                    className='btn btn-secondary btn-sm'
                    onClick={() => setDisplayEnrollment(!displayEnrollment)}
                >{displayEnrollment ? "Amaga matrícula" : "Mostra matrícula"}</button>
            </>
        );

    const renderEnrollment = () => {
        if (!person.enrolled) return null;

        return (
            <div className="animate-fade-in p-6 sm:px-8">
                {person.groupDescription ?
                    <p className='mb-4'>
                        <span className="text-sm text-slate-500">Curs</span>
                        <span className="block font-semibold text-slate-900">{person.groupDescription}</span>
                    </p> : null}
                {
                    person.enrollmentSubjectsInfo ? <>
                        <h3 className='text-sm font-semibold uppercase tracking-wider text-slate-500'>Assignatures a les que s&apos;ha matriculat</h3>
                        <ul className='mt-3 divide-y divide-slate-100 rounded-lg ring-1 ring-slate-200'>
                            {person.enrollmentSubjectsInfo.trim().split("\n").map((x, idx) => (
                                <li key={idx} className="px-4 py-2.5 text-slate-700">{x}</li>
                            ))}
                        </ul>
                    </> : null
                }
            </div>
        )
    }

    const initials = person.fullName.split(" ").filter(x => x.length > 0).slice(0, 2).map(x => x[0].toUpperCase()).join("");

    return (
        <div className="card animate-fade-in overflow-hidden">
            <div className='flex items-center justify-between gap-4 border-b border-slate-200 p-6 sm:px-8'>
                <div className="flex min-w-0 items-center gap-3">
                    <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-brand-100 font-semibold text-brand-700">
                        {initials}
                    </div>
                    <div className="min-w-0">
                        <p className="text-xs font-medium uppercase tracking-wider text-slate-400">Alumne</p>
                        <h3 className='truncate font-semibold text-slate-900'>{person.fullName}</h3>
                    </div>
                </div>
                {enrollmentButton}
            </div>
            {displayEnrollment ?
                <>{renderEnrollment()}</> :
                <>
                    {displayEvents()}
                    {displayTotal()}
                    {renderAndSubmitPaymentForm()}
                </>
            }
        </div>
    )
}

interface EventProps {
    idx: number,
    item: Item,
    setEventItem: (idx: number, event: Item) => void,
}

const EventLine = ({ idx, item, setEventItem: setEvent }: EventProps) => {
    const { event, selected, quantity } = item;
    const options = Array.from(Array(item.event.maxQuantity + 1), (_, x) => ({ key: x.toString(), value: x }));

    const onSelectQuantity = (q: string) => {
        const quantity = parseInt(q);
        item.selected = quantity > 0;
        item.quantity = quantity;
        setEvent(idx, item);
    }

    const onSelectEvent = (checked: boolean) => {
        const quantity = checked ? Math.max(item.quantity, 1) : 0;
        item.selected = checked;
        item.quantity = quantity;
        setEvent(idx, item);
    }

    return (
        <div className="flex w-full items-center justify-between gap-4">
            <div className="flex min-w-0 flex-1 items-center">
                <input id={`event_${event.code}`}
                    aria-describedby="helper-checkbox-text"
                    type="checkbox"
                    disabled={!event.selectable}
                    className="h-5 w-5 shrink-0 cursor-pointer rounded disabled:cursor-not-allowed"
                    checked={selected}
                    onChange={(e) => onSelectEvent(e.target.checked)}
                />
                <label htmlFor={`event_${event.code}`} className={`ml-3 min-w-0 flex-1 select-none ${event.selectable ? "cursor-pointer" : "cursor-not-allowed"}`}>
                    <div className="font-medium text-slate-900">
                        {event.name}
                    </div>
                    <div className="mt-0.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-slate-500">
                        <span className="inline-flex items-center gap-1">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-4 w-4">
                                <path strokeLinecap="round" strokeLinejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
                            </svg>
                            {displayDate(event.date)}
                        </span>
                        {
                            event.displayQuantitySelector ?
                                <span>Preu individual: {event.price} {event.currencySymbol}</span>
                                : null
                        }
                    </div>
                </label>
            </div>
            <div className="flex shrink-0 items-center gap-3">
                {
                    event.displayQuantitySelector ?
                        <SelectorComponent
                            id={`"quantity_"${event.code}`}
                            name={`"quantity_"${event.code}`}
                            className="form-input w-auto py-1.5 pl-3 pr-8"
                            selector={{ selected: quantity.toString(), options }}
                            onSelect={onSelectQuantity} /> : null
                }
                <div className={`${event.displayQuantitySelector ? 'hidden sm:block' : ''} min-w-[4rem] text-right font-semibold text-slate-900 tabular-nums`}>
                    {
                        event.displayQuantitySelector ?
                            <>{event.price * quantity} {event.currencySymbol}</> :
                            <>{event.price} {event.currencySymbol}</>
                    }
                </div>
            </div>
        </div>
    );
}
