import Head from 'next/head'
import styles from '@/styles/Index.module.css'
import { Noto_Sans } from '@next/font/google';

const font = Noto_Sans({ weight: '400', subsets: ['devanagari'] })

const Home = () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${font.className}`}>
        Pàgina sense autenticació
      </main>
    </>
  )
}

export default Home