import Head from "next/head";
import { Noto_Sans } from '@next/font/google';
import { DangerAlert } from "@/components/Alerts";

const font = Noto_Sans({ weight: '400', subsets: ['devanagari'] })

const Ko = () => {
    return (<>
        <Head>
            <title>Pagaments - {process.env.SCHOOL_NAME}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${font.className} container mx-auto px-5 mt-10  max-w-xl`}>
            <DangerAlert title="Error durant el pagament"  text="El pagament no s'ha completat. Contacteu amb la vostra entitat bancària." />
        </main>
    </>)
}

export default Ko;