import Head from "next/head";
import { Noto_Sans } from '@next/font/google';
import { SuccessAlert } from "@/components/Alerts";
import { useEffect } from "react";
import { useRouter } from "next/router";

const font = Noto_Sans({ weight: '400', subsets: ['devanagari'] })

const Ok = () => {

    const router = useRouter()

    useEffect(() => {
        console.log("todo: load summary")
        console.log(router.query);
    }, [router])

    return (<>
        <Head>
            <title>Pagaments - IES MOSSÈN ALCOVER</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${font.className} container mx-auto px-5 mt-10  max-w-xl`}>
            <SuccessAlert text="Pagament realitzat correctament" />
        </main>
    </>)
}

export default Ok;