import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { getOrderInfo } from "@/lib/apis/payments";
import { useApiRequest } from "@/lib/hooks/useApiRequest";
import { PublicLayout } from "@/components/layout/PublicLayout";
import { OrderConfirmation } from "@/components/orders/OrderConfirmation";

const Ok = () => {
    const router = useRouter()
    const signatureVersion = router.query["Ds_SignatureVersion"] as string;
    const merchantParameters = router.query["Ds_MerchantParameters"] as string;
    const signature = router.query["Ds_Signature"] as string;
    const { data: orderInfo, isLoading, executeRequest } = useApiRequest(getOrderInfo);

    useEffect(() => {
        if (signature && merchantParameters && signatureVersion) {
            executeRequest(merchantParameters, signature, signatureVersion);
        }
    }, [signatureVersion, merchantParameters, signature])


    if (isLoading || orderInfo == null) return null;

    return (<>
        <Head>
            <title>Pagaments - {process.env.SCHOOL_NAME}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <PublicLayout>
            <OrderConfirmation orderInfo={orderInfo} title="Pagament realitzat correctament" />
        </PublicLayout>
    </>)
}

export default Ok;
