import Head from 'next/head'
import styles from '@/styles/Index.module.css'
import useUser from '@/lib/hooks/useUser'

const Home = () => {

  const { user, loading } = useUser()

  if (loading || !user) {
    return null
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Hello {user.givenName}
      </main>
    </>
  )
}

export default Home