import Head from 'next/head'
import React, { useState } from 'react'
import { useRouter } from 'next/router';
import { signin, SigninStatus } from '@/lib/apis/payments';

const Signin = () => {

  const [error, setError] = useState<string | undefined>()
  const [username, setUsername] = useState<string>("")
  const [password, setPassword] = useState<string>("")
  const router = useRouter()

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const { redirectTo = "/" } = router.query

    const response = await signin(username, password)
    if (response.status == SigninStatus.Ok) {
      router.push(redirectTo as string)
    }
    else {
      setError(response.errorMessage as string)
    }
    
  }

  const renderError = () => {
    if (!error) return null
    return (
      <span>{error}</span>
    )
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {renderError()}
        <form action="/api/signin" method="post" onSubmit={handleSubmit}>
          <label htmlFor="username"></label>
          <input id="username" type="text" name="username" value={username} onChange={e => setUsername(e.target.value)} />
          <br />
          <label htmlFor="password"></label>
          <input id="password" type="password" name="password" value={password} onChange={e => setPassword(e.target.value)} />
          <br />
          <input type="submit" />
        </form>
      </main>
    </>
  )
}

export default Signin