import Head from 'next/head'
import React, { useState } from 'react'
import { useRouter } from 'next/router';
import { signin, SigninStatus } from '@/lib/apis/payments';

const Signin = () => {

  const [error, setError] = useState<string | undefined>()
  const [username, setUsername] = useState<string>("")
  const [password, setPassword] = useState<string>("")
  const router = useRouter()

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    const { redirectTo = "/" } = router.query

    const response = await signin(username, password)
    if (response.status == SigninStatus.Ok) {
      router.push(redirectTo as string)
    }
    else {
      setError(response.errorMessage as string)
    }

  }

  const renderError = () => {
    if (!error) return null
    return (
      <span>{error}</span>
    )
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {renderError()}

        <div className="max-w-lg m-auto">
          <div className="mt-12">
            <p className="text-lg font-medium text-gray-900 dark:text-white">Accés Administratiu</p>
          </div>
          <div className="mb-6">
            <hr />
          </div>
          <form action="/api/signin" method="post" onSubmit={handleSubmit}>
            <div className="mb-6">
              <label htmlFor="username" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Usuari</label>
              <input
                type="text"
                name="username" value={username} onChange={e => setUsername(e.target.value)}
                id="username"
                className="bg-gray-50 border border-gray-300 text-gray-900 text-sm focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
            </div>
            <div className="mb-6">
              <label htmlFor="password" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Contrasenya</label>
              <input
                type="password"
                id="password"
                value={password} onChange={e => setPassword(e.target.value)}
                className="bg-gray-50 border border-gray-300 text-gray-900 text-sm focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
            </div>

            <button type="submit" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Submit</button>
          </form>
        </div>
      </main>
    </>
  )
}

export default Signin