import { SuccessAlert } from "@/components/Alerts";
import { createEvent } from "@/lib/apis/payments/client";
import { Event } from "@/lib/apis/payments/models";
import { useState } from "react";
import EventFields from "@/components/events/EventFields";
import { Container } from "@/components/layout/SideBar";
import Head from "next/head";
import Link from "next/link";
import { PageHeader, PageMain } from "@/components/layout/PageHeader";
import { useApiRequest } from "@/lib/hooks/useApiRequest";

const defaultEvent: Event = {
    id: 0,
    code: "",
    name: "",
    description: "",
    date: new Date().toISOString(),
    price: 0,
    amipaPrice: 0,
    maxQuantity: 1,
    publishDate: new Date().toISOString(),
    unpublishDate: undefined,
    enrollment: false,
    amipa: false
};


const Create = () => {
    const [event, setEvent] = useState(defaultEvent);
    const [created, setCreated] = useState(false);
    const { data: code, errors, isLoading, executeRequest } = useApiRequest(createEvent);

    const onSubmit = async (e: Event) => {
        const ok = await executeRequest(e);
        if (ok) {
            setCreated(true);
        }
    }

    const onFormSubmit = async (e: React.SyntheticEvent<HTMLFormElement>) => {
        e.preventDefault();
        onSubmit(event);
    }

    const formDisabled = () => isLoading;

    return (
        <>
            <Head>
                <title>Afegir esdeveniment - {process.env.SCHOOL_NAME}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageMain narrow>
                <PageHeader title="Nou esdeveniment" back={{ href: "/admin/events", text: "Esdeveniments" }} />
                <div className="card p-6 sm:p-8">
                        {created ?
                            <SuccessAlert text={`Event afegit correctament el codi de l'event és: ${code}`}>
                                <div className="mt-3 flex flex-wrap gap-2">
                                    <Link className="btn btn-success btn-sm" href={`/admin/events/${code}/people`}>
                                        Afegir persones a l&apos;esdeveniment
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="h-4 w-4">
                                            <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                                        </svg>
                                    </Link>
                                    <Link className="btn btn-secondary btn-sm" href="/admin/events">Tornar als esdeveniments</Link>
                                </div>
                            </SuccessAlert> :
                            <form action="#" method="post" onSubmit={onFormSubmit} autoComplete="off">
                                <EventFields
                                    errors={errors}
                                    event={event}
                                    setEvent={setEvent} />
                                <div>
                                    <input
                                        disabled={formDisabled()}
                                        className="btn btn-primary mt-8 w-full"
                                        value="Crear esdeveniment"
                                        type="submit" />
                                </div>
                            </form>
                        }
                    </div>
            </PageMain>
        </>

    )
}

export default function CreateEventPage() {
    return (
        <Container>
            <Create />
        </Container>
    )
};