import { Spinner } from "@/components/Loading";
import Table, { Row } from "@/components/Table";
import { EventsRow, getEventsView } from "@/lib/apis/payments";
import Head from "next/head";
import { useEffect, useState } from "react";

const Events = () => {

    const [events, setEvents] = useState<EventsRow[]>([])
    const [loadingEvents, setLoadingEvents] = useState(false)
    const tableHeaders: string[] = ["Codi", "Nom", "Preu", "Preu Amipa", "Dia Publicació", "Dia Expiració", "Actiu?"];

    useEffect(() => {
        setLoadingEvents(true);
        getEventsView()
            .then(x => setEvents(x))
            .finally(() => setLoadingEvents(false));
    }, []);

    const mapToRow = (): Row[] => {
        const now = new Date();
        return events.map(x => {
            const from = new Date(x.publishDate);
            const to = new Date(x.unpublishDate);
            const active = x.isActive ? "Si" : "No";

            return { key: x.id, values: [ x.code, x.name, `${x.price}`, `${x.amipaPrice}`, from.toLocaleDateString() ,to.toLocaleDateString(), active] };
        });
    }

    const listEvents = () => {
        if (loadingEvents) return null;
        return (
            <Table
                paging={false}
                headers={tableHeaders}
                rows={mapToRow()}
            />
        )
    }

    if (loadingEvents ) {
        return null
    }

    return (

        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className='flex justify-start items-center mb-4'>
                    {loadingEvents ? <Spinner /> : null }
                    {loadingEvents ? <p>Carregant Informació</p> : null}
                </div>
                {listEvents()}
            </main>
            
        </>
    );
}

export default Events;