import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useRouter } from 'next/router';
import { signin, signinOAuth, SigninResponse, SigninStatus } from '@/lib/apis/payments';
import { CredentialResponse, GoogleLogin, GoogleOAuthProvider } from '@react-oauth/google';
import { DangerAlert } from '@/components/Alerts';
import { useApiRequest } from '@/lib/hooks/useApiRequest';

const Signin = () => {
  const { data, executeRequest: signinRequest } = useApiRequest(signin);
  const [error, setError] = useState<string | undefined>()
  const [username, setUsername] = useState<string>("")
  const [password, setPassword] = useState<string>("")
  const router = useRouter()

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    signinRequest(username, password);
  }

  useEffect(() => {
    if (data) handleSigninResponse(data);
  }, [data]);

  const onGoogleLogin = async (cr: CredentialResponse) => {
    const { credential } = cr;
    if (credential)
    {
      const response = await signinOAuth(credential);
      handleSigninResponse(response);
    }
  }

  const handleSigninResponse = (response: SigninResponse) => {
    const { redirectTo = "/admin" } = router.query
    if (response.status == SigninStatus.Ok) {
      router.push(redirectTo as string)
    }
    else {
      setError(response.errorMessage as string)
    }
  }

  const renderError = () => {
    if (!error) return null
    return (
      <DangerAlert title="Error d'accés" text={error} />
    )
  }


  return (
    <>
      <Head>
        <title>Iniciar sessió - {process.env.SCHOOL_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-50 via-white to-brand-50 px-4 py-12">
        <div className="animate-fade-in w-full max-w-sm">
          <div className="px-2 py-10 text-center sm:rounded-xl sm:bg-white sm:px-8 sm:shadow-sm sm:ring-1 sm:ring-slate-200/80">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-brand-500 to-brand-700 text-white shadow-lg shadow-brand-600/30">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.8} stroke="currentColor" className="h-6 w-6">
                <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-16.5 5.25h6m-6 2.25h3m-3.75 3h15a2.25 2.25 0 002.25-2.25V6.75A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25v10.5A2.25 2.25 0 004.5 19.5z" />
              </svg>
            </div>
            <h1 className="mt-6 text-2xl font-bold tracking-tight text-slate-900">Accés Administratiu</h1>
            <p className="mt-1 text-sm text-slate-500">{process.env.SCHOOL_NAME}</p>

            {error &&
              <div className="mt-6 text-left">
                {renderError()}
              </div>
            }

            <div className="mt-8 flex justify-center">
              <GoogleLogin
                onSuccess={onGoogleLogin}
                onError={() => {
                  setError("Login Failed")
                }}
              />
            </div>

            {/* <div
              className="my-6 flex items-center before:flex-1 before:border-t before:border-slate-200 after:flex-1 after:border-t after:border-slate-200">
              <p
                className="mx-4 mb-0 text-center text-sm text-slate-400">
                O bé
              </p>
            </div>

            <form className="space-y-5 text-left" action="/api/signin" method="post" onSubmit={handleSubmit}>
              <div>
                <label htmlFor="username" className="form-label">Usuari</label>
                <input
                  type="text"
                  autoComplete="username"
                  name="username" value={username} onChange={e => setUsername(e.target.value)}
                  id="username"
                  className="form-input" required />
              </div>
              <div>
                <label htmlFor="password" className="form-label">Contrasenya</label>
                <input
                  type="password"
                  id="password"
                  autoComplete="current-password"
                  value={password} onChange={e => setPassword(e.target.value)}
                  className="form-input" required />
              </div>

              <button type="submit" className="btn btn-primary w-full">Inicia sessió</button>
            </form> */}
          </div>
        </div>
      </main>
    </>
  )
}


const SingInPage = () => {
  return <GoogleOAuthProvider clientId={process.env.CLIENT_ID_GOOGLE as string}><Signin /></GoogleOAuthProvider>;
}

// const SingInPage = () => {
//   return <Signin />;
// }

export default SingInPage