name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: 12
    - run: npm install
    - run: npm run export
