# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
      - run: npm ci
      - name: Configure AWS Client
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRETACCESSKEY}}
          aws-region: ${{ secrets.AWS_S3_REGION }}
      - name: Create Zip
        uses: vimtor/action-zip@v1
        with:
          files: ./
          dest: next-payments-app.zip
      - name: Configure AWS Client
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRETACCESSKEY}}
          aws-region: ${{ secrets.AWS_S3_REGION }}
      - name: Copy to S3
        run: aws s3 cp next-payments-app.zip s3://${{ secrets.AWS_S3_AWSBUCKET }}
      - name: Create AWS Deploy
        run: aws deploy create-deployment --application-name PaymentsApp --deployment-group-name ${{ secrets.AWS_DEPLOYMENT_GROUP }} --s3-location bucket=${{ secrets.AWS_S3_AWSBUCKET }},key=next-payments-app.zip,bundleType=zip
